# Generated by Django 5.2.5 on 2026-03-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shiped',
            field=models.BooleanField(default=False),
        ),
    ]
