# Generated by Django 5.2.5 on 2026-03-30 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_order_shiped'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shiped',
            new_name='shipped',
        ),
    ]
